title: KickstarterProjectDetails
description: This dataset contains information and details about the Kickstarter Projects  undertaken from 2009 to 2017. It is very detailed and constains information about  the money goal and those pledged, the dates of start and deadllines as well.
show_downloads: true
theme: jekyll-theme-leap-day